// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: src/LexicalAnalizer/LexerCup.flex

package LexicalAnalizer;
import java_cup.runtime.*;



@SuppressWarnings("fallthrough")
public class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;
  public static final int CHAR = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2, 2
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\1\6\1\7\3\0\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\11\22\2\0"+
    "\1\23\1\24\1\25\1\0\1\26\32\27\1\30\1\31"+
    "\1\32\1\33\1\34\1\0\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\27\1\46\1\47"+
    "\1\27\1\50\1\51\1\52\1\27\1\53\1\54\1\55"+
    "\1\56\1\57\4\27\1\60\1\61\1\62\1\63\6\0"+
    "\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\2\16\1\17"+
    "\1\1\1\20\1\2\1\21\1\22\1\23\1\24\15\21"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\31\1\33"+
    "\4\31\1\34\1\35\1\34\1\1\4\34\1\36\1\37"+
    "\1\40\1\41\1\0\1\42\1\43\1\44\1\0\1\2"+
    "\3\21\1\45\5\21\1\46\10\21\1\43\1\47\1\50"+
    "\1\51\1\52\4\31\1\43\5\0\1\53\1\54\7\21"+
    "\1\55\12\21\4\31\5\0\2\21\1\56\1\57\1\60"+
    "\4\21\1\61\1\21\1\62\2\21\1\63\1\21\1\64"+
    "\1\61\1\31\1\62\1\64\1\61\1\0\1\62\1\64"+
    "\1\21\1\65\1\66\1\67\2\21\1\70\2\21\1\71"+
    "\2\70\3\21\1\72\1\73\1\74\1\21\1\75\1\76";

  private static int [] zzUnpackAction() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\234\0\320\0\u0104\0\234"+
    "\0\234\0\234\0\234\0\234\0\u0138\0\u016c\0\234\0\u01a0"+
    "\0\u01d4\0\u0208\0\u023c\0\u0270\0\u02a4\0\u02d8\0\u030c\0\u0340"+
    "\0\234\0\234\0\234\0\u0374\0\u03a8\0\u03dc\0\u0410\0\u0444"+
    "\0\u0478\0\u04ac\0\u04e0\0\u0514\0\u0548\0\u057c\0\u05b0\0\u05e4"+
    "\0\234\0\234\0\234\0\234\0\u0618\0\234\0\u064c\0\u0680"+
    "\0\u06b4\0\u06e8\0\u071c\0\u0750\0\234\0\234\0\u0784\0\u07b8"+
    "\0\u07ec\0\u0820\0\u0854\0\u0888\0\234\0\234\0\234\0\234"+
    "\0\u08bc\0\u08f0\0\u0924\0\234\0\u0958\0\u098c\0\u09c0\0\u09f4"+
    "\0\u0a28\0\u0340\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u0340"+
    "\0\u0b60\0\u0b94\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc"+
    "\0\u0618\0\234\0\234\0\234\0\234\0\u0d00\0\u0d34\0\u0d68"+
    "\0\u0d9c\0\234\0\u0dd0\0\u0e04\0\u0e38\0\u0e6c\0\u0ea0\0\234"+
    "\0\234\0\u0ed4\0\u0f08\0\u0f3c\0\u0f70\0\u0fa4\0\u0fd8\0\u100c"+
    "\0\u0340\0\u1040\0\u1074\0\u10a8\0\u10dc\0\u1110\0\u1144\0\u1178"+
    "\0\u11ac\0\u11e0\0\u1214\0\u1248\0\u127c\0\u12b0\0\u12e4\0\u1318"+
    "\0\u134c\0\u1380\0\u13b4\0\u13e8\0\u141c\0\u1450\0\u0340\0\u0340"+
    "\0\u0340\0\u1484\0\u14b8\0\u14ec\0\u1520\0\u0340\0\u1554\0\u0340"+
    "\0\u1588\0\u15bc\0\u0340\0\u15f0\0\u0340\0\u0618\0\u1624\0\u0618"+
    "\0\u0618\0\234\0\u1658\0\234\0\234\0\u168c\0\u0340\0\u0340"+
    "\0\u0340\0\u16c0\0\u16f4\0\u0340\0\u1728\0\u175c\0\u0340\0\u0618"+
    "\0\234\0\u1790\0\u17c4\0\u17f8\0\u0340\0\u0340\0\u0340\0\u182c"+
    "\0\u0340\0\u0340";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\2\5\1\0\1\6\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\1\17\1\20\1\4\1\21"+
    "\1\22\1\23\1\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\4\1\32\1\33\2\30\1\34\1\35\1\36\1\37"+
    "\1\40\2\30\1\41\2\30\1\42\1\30\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\2\55\1\0\1\55\1\0\1\55\1\56\14\55\1\57"+
    "\5\55\1\60\16\55\1\61\1\55\1\62\1\63\3\55"+
    "\1\64\4\55\2\65\1\0\1\65\1\0\3\65\1\66"+
    "\12\65\1\67\5\65\1\70\16\65\1\71\1\65\1\72"+
    "\1\73\3\65\1\74\4\65\66\0\1\5\105\0\1\75"+
    "\52\0\1\76\64\0\1\77\65\0\1\100\3\0\1\23"+
    "\75\0\1\101\46\0\1\102\1\0\2\102\60\0\1\102"+
    "\1\0\2\23\65\0\1\103\63\0\1\104\63\0\1\105"+
    "\37\0\1\106\2\27\1\106\1\27\21\106\1\0\35\106"+
    "\21\0\2\30\4\0\1\30\4\0\24\30\25\0\2\30"+
    "\4\0\1\30\4\0\15\30\1\107\1\30\1\110\4\30"+
    "\25\0\2\30\4\0\1\30\4\0\10\30\1\111\13\30"+
    "\25\0\2\30\4\0\1\30\4\0\15\30\1\112\6\30"+
    "\25\0\2\30\4\0\1\30\4\0\13\30\1\113\10\30"+
    "\25\0\2\30\4\0\1\30\4\0\1\30\1\114\11\30"+
    "\1\115\1\30\1\116\4\30\1\117\1\30\25\0\2\30"+
    "\4\0\1\30\4\0\6\30\1\120\5\30\1\121\7\30"+
    "\25\0\2\30\4\0\1\30\4\0\22\30\1\122\1\30"+
    "\25\0\2\30\4\0\1\30\4\0\17\30\1\123\4\30"+
    "\25\0\2\30\4\0\1\30\4\0\5\30\1\124\16\30"+
    "\25\0\2\30\4\0\1\30\4\0\21\30\1\125\2\30"+
    "\25\0\2\30\4\0\1\30\4\0\17\30\1\126\4\30"+
    "\25\0\2\30\4\0\1\30\4\0\14\30\1\127\7\30"+
    "\25\0\2\30\4\0\1\30\4\0\15\30\1\130\6\30"+
    "\4\0\2\55\1\0\1\55\1\0\1\55\1\0\22\55"+
    "\1\0\34\55\1\0\1\55\1\0\1\55\1\0\15\55"+
    "\1\131\4\55\1\0\32\55\6\0\1\132\41\0\1\133"+
    "\2\0\1\134\1\0\1\135\6\0\2\55\1\0\1\55"+
    "\1\0\1\55\1\0\22\55\1\0\24\55\1\136\7\55"+
    "\1\0\1\55\1\0\1\55\1\0\22\55\1\0\21\55"+
    "\1\137\12\55\1\0\1\55\1\0\1\55\1\0\22\55"+
    "\1\0\7\55\1\140\24\55\1\0\1\55\1\0\1\55"+
    "\1\0\22\55\1\0\17\55\1\141\12\55\24\0\1\142"+
    "\47\0\1\65\37\0\1\65\2\0\1\65\1\0\1\65"+
    "\64\0\1\143\60\0\1\144\51\0\1\145\73\0\1\146"+
    "\12\0\34\101\1\147\27\101\21\0\2\102\65\0\1\150"+
    "\63\0\1\151\37\0\2\106\1\0\23\106\1\0\35\106"+
    "\21\0\2\30\4\0\1\30\4\0\15\30\1\152\6\30"+
    "\25\0\2\30\4\0\1\30\4\0\5\30\1\153\16\30"+
    "\25\0\2\30\4\0\1\30\4\0\1\30\1\154\22\30"+
    "\25\0\2\30\4\0\1\30\4\0\11\30\1\155\6\30"+
    "\1\156\3\30\25\0\2\30\4\0\1\30\4\0\13\30"+
    "\1\157\10\30\25\0\2\30\4\0\1\30\4\0\15\30"+
    "\1\160\6\30\25\0\2\30\4\0\1\30\4\0\17\30"+
    "\1\161\4\30\25\0\2\30\4\0\1\30\4\0\14\30"+
    "\1\162\7\30\25\0\2\30\4\0\1\30\4\0\21\30"+
    "\1\163\2\30\25\0\2\30\4\0\1\30\4\0\13\30"+
    "\1\164\10\30\25\0\2\30\4\0\1\30\4\0\11\30"+
    "\1\165\12\30\25\0\2\30\4\0\1\30\4\0\1\30"+
    "\1\166\17\30\1\167\2\30\25\0\2\30\4\0\1\30"+
    "\4\0\17\30\1\170\4\30\25\0\2\30\4\0\1\30"+
    "\4\0\22\30\1\171\1\30\25\0\2\30\4\0\1\30"+
    "\4\0\21\30\1\172\2\30\25\0\2\30\4\0\1\30"+
    "\4\0\11\30\1\173\12\30\4\0\2\55\1\0\1\55"+
    "\1\0\1\55\1\0\22\55\1\0\15\55\1\174\16\55"+
    "\1\0\1\55\1\0\1\55\1\0\22\55\1\0\13\55"+
    "\1\175\20\55\1\0\1\55\1\0\1\55\1\0\22\55"+
    "\1\0\3\55\1\176\30\55\1\0\1\55\1\0\1\55"+
    "\1\0\22\55\1\0\13\55\1\177\16\55\47\0\1\200"+
    "\61\0\1\201\53\0\1\202\73\0\1\203\16\0\20\101"+
    "\1\5\13\101\1\204\27\101\21\0\2\30\4\0\1\30"+
    "\4\0\13\30\1\205\10\30\25\0\2\30\4\0\1\30"+
    "\4\0\1\30\1\206\22\30\25\0\2\30\4\0\1\30"+
    "\4\0\17\30\1\207\4\30\25\0\2\30\4\0\1\30"+
    "\4\0\6\30\1\210\15\30\25\0\2\30\4\0\1\30"+
    "\4\0\5\30\1\211\16\30\25\0\2\30\4\0\1\30"+
    "\4\0\20\30\1\212\3\30\25\0\2\30\4\0\1\30"+
    "\4\0\1\30\1\213\22\30\25\0\2\30\4\0\1\30"+
    "\4\0\3\30\1\214\20\30\25\0\2\30\4\0\1\30"+
    "\4\0\5\30\1\215\16\30\25\0\2\30\4\0\1\30"+
    "\4\0\13\30\1\216\10\30\25\0\2\30\4\0\1\30"+
    "\4\0\14\30\1\217\7\30\25\0\2\30\4\0\1\30"+
    "\4\0\4\30\1\220\17\30\25\0\2\30\4\0\1\30"+
    "\4\0\22\30\1\221\1\30\25\0\2\30\4\0\1\30"+
    "\4\0\11\30\1\222\12\30\25\0\2\30\4\0\1\30"+
    "\4\0\5\30\1\223\16\30\25\0\2\30\4\0\1\30"+
    "\4\0\11\30\1\224\12\30\25\0\2\30\4\0\1\30"+
    "\4\0\4\30\1\225\17\30\4\0\2\55\1\0\1\55"+
    "\1\0\1\55\1\0\22\55\1\0\15\55\1\226\16\55"+
    "\1\0\1\55\1\0\1\55\1\0\22\55\1\0\16\55"+
    "\1\227\15\55\1\0\1\55\1\0\1\55\1\0\22\55"+
    "\1\0\6\55\1\230\25\55\1\0\1\55\1\0\1\55"+
    "\1\0\22\55\1\0\6\55\1\231\23\55\47\0\1\232"+
    "\64\0\1\233\53\0\1\234\63\0\1\235\23\0\20\101"+
    "\1\0\13\101\1\204\27\101\21\0\2\30\4\0\1\30"+
    "\4\0\5\30\1\236\16\30\25\0\2\30\4\0\1\30"+
    "\4\0\12\30\1\237\11\30\25\0\2\30\4\0\1\30"+
    "\4\0\5\30\1\240\16\30\25\0\2\30\4\0\1\30"+
    "\4\0\21\30\1\241\2\30\25\0\2\30\4\0\1\30"+
    "\4\0\21\30\1\242\2\30\25\0\2\30\4\0\1\30"+
    "\4\0\7\30\1\243\14\30\25\0\2\30\4\0\1\30"+
    "\4\0\21\30\1\244\2\30\25\0\2\30\4\0\1\30"+
    "\4\0\17\30\1\245\4\30\25\0\2\30\4\0\1\30"+
    "\4\0\14\30\1\246\7\30\25\0\2\30\4\0\1\30"+
    "\4\0\13\30\1\247\10\30\4\0\2\55\1\0\1\55"+
    "\1\0\1\55\1\0\22\55\1\0\23\55\1\250\6\55"+
    "\55\0\1\251\27\0\2\30\4\0\1\30\4\0\1\30"+
    "\1\252\22\30\25\0\2\30\4\0\1\30\4\0\11\30"+
    "\1\253\12\30\25\0\2\30\4\0\1\30\4\0\5\30"+
    "\1\254\16\30\25\0\2\30\4\0\1\30\4\0\14\30"+
    "\1\255\7\30\25\0\2\30\4\0\1\30\4\0\7\30"+
    "\1\256\14\30\25\0\2\30\4\0\1\30\4\0\14\30"+
    "\1\257\7\30\25\0\2\30\4\0\1\30\4\0\15\30"+
    "\1\260\6\30\25\0\2\30\4\0\1\30\4\0\17\30"+
    "\1\261\4\30\25\0\2\30\4\0\1\30\4\0\14\30"+
    "\1\262\7\30\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[6240];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\2\11\2\1\5\11\2\1\1\11\11\1\3\11"+
    "\15\1\4\11\1\1\1\11\6\1\2\11\6\1\4\11"+
    "\1\0\2\1\1\11\1\0\24\1\4\11\4\1\1\11"+
    "\5\0\2\11\26\1\5\0\25\1\1\11\1\0\2\11"+
    "\13\1\1\11\11\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    StringBuffer string = new StringBuffer();

    StringBuffer charBuff = new StringBuffer();

    private Symbol symbol(int type) {
        
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value) {
        
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return symbol(sym.ERRORNOTRECOGNIZED);
            }
          // fall through
          case 63: break;
          case 2:
            { /*skip*/
            }
          // fall through
          case 64: break;
          case 3:
            { return symbol(sym.BALTASAR);
            }
          // fall through
          case 65: break;
          case 4:
            { string.setLength(0); yybegin(STRING);
            }
          // fall through
          case 66: break;
          case 5:
            { return symbol(sym.MELCHOR);
            }
          // fall through
          case 67: break;
          case 6:
            { charBuff.setLength(0); yybegin(CHAR);
            }
          // fall through
          case 68: break;
          case 7:
            { return symbol(sym.ABRECUENTO);
            }
          // fall through
          case 69: break;
          case 8:
            { return symbol(sym.CIERRACUENTO);
            }
          // fall through
          case 70: break;
          case 9:
            { return symbol(sym.RELAMPAGO);
            }
          // fall through
          case 71: break;
          case 10:
            { return symbol(sym.RODOLFO);
            }
          // fall through
          case 72: break;
          case 11:
            { return symbol(sym.CHIMENEA);
            }
          // fall through
          case 73: break;
          case 12:
            { return symbol(sym.TRUENO);
            }
          // fall through
          case 74: break;
          case 13:
            { return symbol(sym.JUGUETON);
            }
          // fall through
          case 75: break;
          case 14:
            { return symbol(sym.l_NOEL);
            }
          // fall through
          case 76: break;
          case 15:
            { return symbol(sym.MINSTIX);
            }
          // fall through
          case 77: break;
          case 16:
            { return symbol(sym.UPATREE);
            }
          // fall through
          case 78: break;
          case 17:
            { return symbol(sym.PERSONA);
            }
          // fall through
          case 79: break;
          case 18:
            { return symbol(sym.ABREEMPAQUE);
            }
          // fall through
          case 80: break;
          case 19:
            { return symbol(sym.CIERRAEMPAQUE);
            }
          // fall through
          case 81: break;
          case 20:
            { return symbol(sym.GASPAR);
            }
          // fall through
          case 82: break;
          case 21:
            { return symbol(sym.ABREREGALO);
            }
          // fall through
          case 83: break;
          case 22:
            { return symbol(sym.FINREGALO);
            }
          // fall through
          case 84: break;
          case 23:
            { return symbol(sym.CIERRAREGALO);
            }
          // fall through
          case 85: break;
          case 24:
            { return symbol(sym.CUPIDO);
            }
          // fall through
          case 86: break;
          case 25:
            { string.append( yytext() );
            }
          // fall through
          case 87: break;
          case 26:
            { yybegin(YYINITIAL); 
                                       return symbol(sym.l_SANTA, 
                                       "\""+string.toString()+"\"");
            }
          // fall through
          case 88: break;
          case 27:
            { string.append('\\');
            }
          // fall through
          case 89: break;
          case 28:
            { if (charBuff.length() == 0) {
            charBuff.append(yytext());
        } else {
            return symbol(sym.ERRORNOTRECOGNIZED);
        }
            }
          // fall through
          case 90: break;
          case 29:
            { if (charBuff.length() == 1 || (charBuff.length() == 2 && charBuff.charAt(0) == '\\')) {
            yybegin(YYINITIAL);
            return symbol(sym.l_COLACHO, "\'" + charBuff.toString() + "\'");
        } else {
            return symbol(sym.ERRORNOTRECOGNIZED);
        }
            }
          // fall through
          case 91: break;
          case 30:
            { return symbol(sym.EVERGEEN);
            }
          // fall through
          case 92: break;
          case 31:
            { return symbol(sym.COMETA);
            }
          // fall through
          case 93: break;
          case 32:
            { return symbol(sym.QUIEN);
            }
          // fall through
          case 94: break;
          case 33:
            { return symbol(sym.GRINCH);
            }
          // fall through
          case 95: break;
          case 34:
            { return symbol(sym.l_NICOLAS);
            }
          // fall through
          case 96: break;
          case 35:
            { return symbol(sym.ENTREGA);
            }
          // fall through
          case 97: break;
          case 36:
            { return symbol(sym.ALABASTRO);
            }
          // fall through
          case 98: break;
          case 37:
            { return symbol(sym.HACE);
            }
          // fall through
          case 99: break;
          case 38:
            { return symbol(sym.ELFO);
            }
          // fall through
          case 100: break;
          case 39:
            { string.append('\"');
            }
          // fall through
          case 101: break;
          case 40:
            { string.append('\n');
            }
          // fall through
          case 102: break;
          case 41:
            { string.append('\r');
            }
          // fall through
          case 103: break;
          case 42:
            { string.append('\t');
            }
          // fall through
          case 104: break;
          case 43:
            { return symbol(sym.OPENSLAE);
            }
          // fall through
          case 105: break;
          case 44:
            { return symbol(sym.MARY);
            }
          // fall through
          case 106: break;
          case 45:
            { return symbol(sym.ENVUELVE);
            }
          // fall through
          case 107: break;
          case 46:
            { return symbol(sym.COLACHO);
            }
          // fall through
          case 108: break;
          case 47:
            { return symbol(sym.HADA);
            }
          // fall through
          case 109: break;
          case 48:
            { return symbol(sym.DUENDE);
            }
          // fall through
          case 110: break;
          case 49:
            { return symbol(sym.NARIZROJA);
            }
          // fall through
          case 111: break;
          case 50:
            { return symbol(sym.ESCUCHA);
            }
          // fall through
          case 112: break;
          case 51:
            { return symbol(sym.l_t_CLAUS);
            }
          // fall through
          case 113: break;
          case 52:
            { return symbol(sym.SINREGALO);
            }
          // fall through
          case 114: break;
          case 53:
            { return symbol(sym.CORTA);
            }
          // fall through
          case 115: break;
          case 54:
            { return symbol(sym.l_f_CLAUS);
            }
          // fall through
          case 116: break;
          case 55:
            { return symbol(sym.NICOLAS);
            }
          // fall through
          case 117: break;
          case 56:
            { return symbol(sym.NARRA);
            }
          // fall through
          case 118: break;
          case 57:
            { return symbol(sym.REVISA);
            }
          // fall through
          case 119: break;
          case 58:
            { return symbol(sym.ENVIA);
            }
          // fall through
          case 120: break;
          case 59:
            { return symbol(sym.SANTA);
            }
          // fall through
          case 121: break;
          case 60:
            { return symbol(sym.CLAUS);
            }
          // fall through
          case 122: break;
          case 61:
            { return symbol(sym.NOEL);
            }
          // fall through
          case 123: break;
          case 62:
            { return symbol(sym.RECORRIDO);
            }
          // fall through
          case 124: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
