
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package LexicalAnalizer;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int RECORRIDO = 51;
  public static final int NICOLAS = 3;
  public static final int MINSTIX = 33;
  public static final int l_SANTA = 16;
  public static final int CHIMENEA = 13;
  public static final int FINREGALO = 53;
  public static final int HADA = 19;
  public static final int PERSONA = 52;
  public static final int CIERRACUENTO = 8;
  public static final int l_COLACHO = 17;
  public static final int ERRORNOTRECOGNIZED = 54;
  public static final int DUENDE = 20;
  public static final int ENTREGA = 39;
  public static final int CIERRAREGALO = 12;
  public static final int NARIZROJA = 28;
  public static final int ABREEMPAQUE = 9;
  public static final int l_NOEL = 15;
  public static final int RODOLFO = 44;
  public static final int RELAMPAGO = 46;
  public static final int CIERRAEMPAQUE = 10;
  public static final int JUGUETON = 47;
  public static final int MARY = 34;
  public static final int NARRA = 26;
  public static final int HACE = 22;
  public static final int l_f_CLAUS = 41;
  public static final int ENVUELVE = 21;
  public static final int COMETA = 48;
  public static final int UPATREE = 32;
  public static final int GRINCH = 42;
  public static final int l_t_CLAUS = 40;
  public static final int EOF = 0;
  public static final int CORTA = 25;
  public static final int MELCHOR = 37;
  public static final int REVISA = 23;
  public static final int l_NICOLAS = 14;
  public static final int TRUENO = 45;
  public static final int error = 1;
  public static final int BALTASAR = 38;
  public static final int NOEL = 2;
  public static final int GASPAR = 36;
  public static final int ABRECUENTO = 7;
  public static final int EVERGEEN = 31;
  public static final int ESCUCHA = 27;
  public static final int ABREREGALO = 11;
  public static final int CUPIDO = 49;
  public static final int ENVIA = 24;
  public static final int SINREGALO = 29;
  public static final int MAINNAVIDAD = 50;
  public static final int CLAUS = 6;
  public static final int COLACHO = 5;
  public static final int ALABASTRO = 30;
  public static final int SANTA = 4;
  public static final int ELFO = 18;
  public static final int QUIEN = 43;
  public static final int OPENSLAE = 35;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NOEL",
  "NICOLAS",
  "SANTA",
  "COLACHO",
  "CLAUS",
  "ABRECUENTO",
  "CIERRACUENTO",
  "ABREEMPAQUE",
  "CIERRAEMPAQUE",
  "ABREREGALO",
  "CIERRAREGALO",
  "CHIMENEA",
  "l_NICOLAS",
  "l_NOEL",
  "l_SANTA",
  "l_COLACHO",
  "ELFO",
  "HADA",
  "DUENDE",
  "ENVUELVE",
  "HACE",
  "REVISA",
  "ENVIA",
  "CORTA",
  "NARRA",
  "ESCUCHA",
  "NARIZROJA",
  "SINREGALO",
  "ALABASTRO",
  "EVERGEEN",
  "UPATREE",
  "MINSTIX",
  "MARY",
  "OPENSLAE",
  "GASPAR",
  "MELCHOR",
  "BALTASAR",
  "ENTREGA",
  "l_t_CLAUS",
  "l_f_CLAUS",
  "GRINCH",
  "QUIEN",
  "RODOLFO",
  "TRUENO",
  "RELAMPAGO",
  "JUGUETON",
  "COMETA",
  "CUPIDO",
  "MAINNAVIDAD",
  "RECORRIDO",
  "PERSONA",
  "FINREGALO",
  "ERRORNOTRECOGNIZED"
  };
}

